spring:
  application:
    name: web-data
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://39.105.125.176:3306/jc_sjs?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:chg}
    password: ${SPRING_DATASOURCE_PASSWORD:chg970723}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    org.apache.ibatis: ${LOG_LEVEL:debug}
    com.exa.mapper: ${LOG_LEVEL:debug}

service:
  stock-exchange-url: http://www.sse.com.cn/disclosure/listedinfo/bulletin/s_docdatesort_desc_2019openpdf.htm
  information-network-url: http://www.cninfo.com.cn/new/disclosure